markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
# Memory Bank configuration
memoryBank:
  location: docs/memory-bank
  autoLoadOnSessionStart: true
  files:
    - projectbrief.md
    - productContext.md
    - systemPatterns.md
    - techContext.md
    - activeContext.md
    - progress.md
# Development Journal configuration
devJournal:
  location: docs/devJournal
  namePattern: YYYYMMDD-NN.md
  autoCreateAfterSession: true
  includeInMemoryBank: true
# Architectural Decision Records configuration
adr:
  location: docs/adr
  namePattern: adr-NNNN.md
  templateFile: templates/adr-tmpl.md
  autoLinkToMemoryBank: true
# Sprint Management configuration
sprint:
  reviewChecklistPath: checklists/sprint-review-checklist.md
  sessionKickoffChecklistPath: checklists/session-kickoff-checklist.md
  enableSprintPlanning: true
  sprintPlanningTemplate: templates/sprint-planning-tmpl.yaml
