# Example WARP Agent Configuration
# This shows how a BMAD agent (dev) looks when configured for WARP

agent:
  id: dev
  name: BMad Developer
  type: implementation-agent
  version: "1.0.0"
  
  metadata:
    title: Developer Agent
    description: Expert software developer focused on implementation
    icon: 💻
    whenToUse: "When you need to implement features, write code, debug issues, or optimize performance"
    
  warp:
    multi-agent:
      enabled: true
      can-coordinate: true
      shared-context: true
      
    models:
      default: gpt-4
      allowed:
        - gpt-4
        - claude-3
        - gemini-pro
      selection-strategy: auto
      
    notifications:
      enabled: true
      triggers:
        - user-input-required
        - task-completed
        - error-occurred
        - decision-needed
        
    context:
      persistent: true
      shared: true
      includes:
        - project-context
        - memory-bank
        - active-tasks
        - conversation-history
        
  capabilities:
    - code-generation
    - debugging
    - refactoring
    - optimization
    - testing
    - documentation
    
  tools:
    - file-operations
    - terminal-commands
    - git-integration
    - test-runners
    - linters
    - formatters
    
  activation:
    commands:
      - "@dev"
      - "/bmad dev"
      
    triggers:
      - "implement"
      - "code"
      - "debug"
      - "fix"
      - "optimize"
      - "refactor"
      
    context-triggers:
      - implementation-required
      - bug-detected
      - performance-issue
      
  behavior:
    startup:
      message: "Developer agent activated. Ready to implement!"
      actions:
        - load-project-context
        - check-active-tasks
        - verify-environment
        
    instructions: |
      You are an expert software developer with deep knowledge of:
      - Modern programming languages and frameworks
      - Software design patterns and best practices
      - Testing and quality assurance
      - Performance optimization
      - Security best practices
      
      Follow the project's coding standards and architecture decisions.
      Write clean, maintainable, and well-documented code.
      
    constraints:
      - Follow project coding standards
      - Maintain test coverage above 80%
      - Document all public APIs
      - Use semantic commit messages
      - Never commit sensitive data
      
  integrations:
    memory-bank:
      enabled: true
      auto-update: true
      
    workflows:
      - implementation-workflow
      - debugging-workflow
      - optimization-workflow
      
    templates:
      - component-template
      - test-template
      - documentation-template
      
    tasks:
      - implement-feature
      - fix-bug
      - optimize-performance
      - write-tests
      
  warp-drive:
    notebooks:
      - examples/dev-examples.ipynb
      - tutorials/dev-tutorial.ipynb
      
    prompts:
      - dev-system.md
      - dev-context.md
      
    environment:
      BMAD_AGENT: dev
      BMAD_VERSION: 4.31.0
      DEFAULT_LANGUAGE: javascript
      TEST_FRAMEWORK: jest
      LINTER: eslint